### ISSUE TITLE
Reverse coloring icons

### ISSUE THREAD

**Issue by qetza** [psake/graphics#2]
Hi,
Would it be possible to have the icons in "reverse" coloring?

For example, if you take this one:
https://github.com/psake/graphics/blob/master/png/psake-single-icon-teal-bg-128x128.png

reverse would mean having the cup in teal with a white powershell icon and transparent background.

**Comment by gep13** [comment]
@sweeneyrobb are you able to help with the above?

**Comment by sweeneyrobb** [comment]
@gep13 i'll create new images for this. should see a PR tomorrow with this.

**Comment by gep13** [comment]
That's great! :+1:
